/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Btn_big: typeof import('~/components/buttons/btnBig.vue')['default']
    BtnBig: typeof import('./../src/components/buttons/btnBig.vue')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    ITablerChevronDown: typeof import('~icons/tabler/chevron-down')['default']
    ITablerColorSwatch: typeof import('~icons/tabler/color-swatch')['default']
    ITablerLanguage: typeof import('~icons/tabler/language')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextField: typeof import('./../src/components/inputs/textField.vue')['default']
  }
}
